files:
  include:
    - src/styles/**/*.scss
  ignore:
    - src/styles/libs/**/*.scss
rules:
  attribute-quotes: 1
  bem-depth: 1
  border-zero: 0
  brace-style: 2
  class-name-format:
    - 1
    -
      allow-leading-underscore: false
  clean-import-paths:
    - 2
    -
      allow-leading-underscore: true
      filename-extensions: false
  declarations-before-nesting: 1
  empty-args:
    - 2
    -
      include: true
  empty-line-between-blocks: 2
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 2
  function-name-format:
    - 1
    -
      allow-leading-underscore: false
  hex-length:
    - 1
    -
      style: long
  hex-notation: 1
  id-name-format:
    - 1
    -
      allow-leading-underscore: false
  indentation: 2
  leading-zero:
    - 2
    -
      include: true
  max-file-line-count: 2
  mixin-name-format:
    - 1
    -
      allow-leading-underscore: false
  mixins-before-declarations: 2
  nesting-depth: 2
  no-color-keywords: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties: 2
  no-trailing-whitespace: 1
  no-warn: 1
  one-declaration-per-line: 1
  placeholder-name-format:
    - 1
    -
      allow-leading-underscore: false
  property-sort-order:
    - 2
    -
      order: concentric
  pseudo-element: 2
  quotes:
    - 1
    -
      style: single
  single-line-per-selector: 0
  space-after-colon: 1
  space-after-comma: 1
  space-around-operator: 1
  space-before-bang: 1
  space-before-brace: 1
  space-before-colon: 1
  space-between-parens: 1
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format:
    - 1
    -
      allow-leading-underscore: false
  zero-unit:
    - 1
    -
      include: true